### ISSUE TITLE
Windows x86 binaries.

### ISSUE THREAD

**Issue by pablorosatti** [moisespr123/PAQCompress#1]
Where can i get de Windows x86 binaries?

**Comment by moisespr123** [comment]
Hi, I have to look up the PAQ exes to make a release of the current version. I'll also be working on this project which has not been updated for years and I've just committed the project here on GitHub. Expect some development in the following days!

**Comment by moisespr123** [comment]
Because of the RAM requirements for the PAQ compressors, it will be available for 64-bit systems only.
