### ISSUE TITLE
Paq8px v173

### ISSUE THREAD

**Issue by SirGryphin** [moisespr123/PAQCompress#2]
Hi, I was wondering if you could make it work with latest paq8px as it has better compression than paq8o10t. I did a quick test and this is what I got.

**paq8o10t**
Level = 8 (Max)
Original Size = 2.10 MB (2,211,840 bytes)
Compressed = 2.08 MB (2,187,264 bytes)

**paq8px v173**
Level = 9 (Max)
Original Size = 2.10 MB (2,211,840 bytes)
Compressed = 1.53 MB (1,613,824 bytes)

**Comment by moisespr123** [comment]
Hi, yes. This software is currently out of date. I'll be writing a new GUI similar to my most recent GUI's and add support for paq8px, which is definitely better than paq8o10t.

**Comment by moisespr123** [comment]
Latest GUI includes the new PAQ8PX versions up to v175.

Download here: https://github.com/moisesmcardona/PAQCompress/releases/tag/v0.1
