### ISSUE TITLE
Paq8sk support?

### ISSUE THREAD

**Issue by pontifezo** [moisespr123/PAQCompress#3]
Hello, thank you for PAQCompress - good convenient GUI for PAQ archivers.
Maybe any plans to add Paq8sk ?

**Comment by moisespr123** [comment]
Yes, I'll consider adding it. It's a fork of paq8pxd.

**Comment by moisespr123** [comment]
Added in v0.3.49: https://github.com/moisespr123/PAQCompress/releases/tag/v0.3.49
