### ISSUE TITLE
Paq8pxv - compression level >9 error

### ISSUE THREAD

**Issue by pontifezo** [moisespr123/PAQCompress#4]
Paq8pxv is not working for me with the compression level higher than 9.
Maybe s9 is the limit? Or using s10...s15 requires more RAM? (I have 16Gb RAM).

**Comment by moisespr123** [comment]
paq8pxd seems to have issues when using higher compression levels. You may want to report this issue here: https://encode.su/threads/1464-Paq8pxd-dict
