### ISSUE TITLE
Question about pxd

### ISSUE THREAD

**Issue by dillfrescott** [moisespr123/PAQCompress#5]
Sorry to bother, but do you know where I can find pre-compiled versions of paq8pxd?

I used to get them from the releases section of https://github.com/kaitz/paq8pxd

But it seems to stop at version 101.

Any help would be appreciated!

-Cross

**Comment by moisespr123** [comment]
Hi, you can find precompiled builds on the encode.su forum here: https://encode.su/threads/1464-Paq8pxd-dict/page36

That forum is where we discuss about data compression.

**Comment by dillfrescott** [comment]
@moisespr123 thank you!!
