### ISSUE TITLE
One last question

### ISSUE THREAD

**Issue by dillfrescott** [moisespr123/PAQCompress#6]
Do you think that paq8px or paq8pxd would be the best at compressing the widest range of files?

As an example, having to compress text, images, binary data, etc... which compressor would usually offer better ratios?

**Comment by moisespr123** [comment]
Both are good compressors. I'd recommend checking the benchmarks in the forum to see how well each compressor works against different file types.

https://encode.su/threads/342-paq8px?p=69505&viewfull=1#post69505

**Comment by dillfrescott** [comment]
@moisespr123 Alright, I'll do that. Thanks again!
